apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: distributed-app
type: Opaque
data:
  # echo -n "votre_valeur" | base64
  postgres-db: ZWNvbW1lcmNl        # ecommerce
  postgres-user: czRsaW91           # s4liou
  postgres-password: czRsaW91QDEyMzQ=  # s4liou@1234